# Generated by Django 5.0.2 on 2024-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.CharField(max_length=5000)),
                ('bot_resposne', models.CharField(max_length=5000)),
            ],
        ),
    ]
