# Generated by Django 5.0.2 on 2024-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_chats_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='bot_resposne',
            new_name='bot_response',
        ),
    ]
